name: Snyk Scan Tools

on:
  workflow_dispatch

jobs:
  snyk-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install Snyk CLI
        run: npm install -g snyk
        
      - name: Authenticate Snyk
        run: snyk auth ${{secrets.SNYK_TOKEN}}

      - name: Run Snyk Code Test
        run: snyk code test
        continue-on-error: true

      - name: Run Snyk Open Source Test
        run: snyk test
        continue-on-error: true

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ml-pipeline:${{github.sha}}
          push: false

      - name: Run Snyk Container Test
        run: snyk container test ml-pipeline:${{github.sha}} --file=Dockerfile
        continue-on-error: true
