name: Snyk Scan Tools

on:
  workflow_dispatch

jobs:
  snyk-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Authenticate Snyk
        run: snyk auth ${{secrets.SNYK_TOKEN}}

